#ifndef __UI_TS_TIRE_SELECT_SUV_H__
#define __UI_TS_TIRE_SELECT_SUV_H__

enum
{
	UITSTSSUV_DISPLAY_AREA_SUV_BODY = 0,
	UITSTSSUV_DISPLAY_AREA_TIRE_01,
	UITSTSSUV_DISPLAY_AREA_TIRE_01_CIRCLE,
	UITSTSSUV_DISPLAY_AREA_TIRE_02,
	UITSTSSUV_DISPLAY_AREA_TIRE_02_CIRCLE,
	UITSTSSUV_DISPLAY_AREA_TIRE_03,
	UITSTSSUV_DISPLAY_AREA_TIRE_03_CIRCLE,
	UITSTSSUV_DISPLAY_AREA_TIRE_04,
	UITSTSSUV_DISPLAY_AREA_TIRE_04_CIRCLE,
	UITSTSSUV_DISPLAY_AREA_TIRE_05,
	UITSTSSUV_DISPLAY_AREA_TIRE_05_CIRCLE,
	UITSTSSUV_DISPLAY_AREA_BACK,
	UITSTSSUV_DISPLAY_AREA_OK,
	UITSTSSUV_DISPLAY_AREA_MAX,
};

extern void ui_ts_tire_select_suv_enter(void);
extern void ui_ts_tire_select_suv_exit(void);
extern void ui_ts_tire_select_suv_show(void);
extern void ui_ts_tire_select_suv_init(void);

#endif
