#ifndef __UI_TP_SUV_H__
#define __UI_TP_SUV_H__

enum
{
	UITPSUV_DISPLAY_AREA_SUV_BODY = 0,
	UITPSUV_DISPLAY_AREA_TIRE_01_TP,
	UITPSUV_DISPLAY_AREA_TIRE_01_TT,
	UITPSUV_DISPLAY_AREA_TIRE_02_TP,
	UITPSUV_DISPLAY_AREA_TIRE_02_TT,
	UITPSUV_DISPLAY_AREA_TIRE_03_TP,
	UITPSUV_DISPLAY_AREA_TIRE_03_TT,
	UITPSUV_DISPLAY_AREA_TIRE_04_TP,
	UITPSUV_DISPLAY_AREA_TIRE_04_TT,
	UITPSUV_DISPLAY_AREA_TIRE_05_TP,
	UITPSUV_DISPLAY_AREA_TIRE_05_TT,
	UITPSUV_DISPLAY_AREA_MAX
};

extern void ui_tp_suv_enter(void);
extern void ui_tp_suv_exit(void);
extern void ui_tp_suv_show(void);
extern void ui_tp_suv_init(void);

#endif
